version: "3"

services:
  sns-app:
    depends_on:
      - db
    container_name: sns-app-test
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - ./.envs/local/.django
      - ./.envs/local/.postgres

  db:
    container_name: db-test
    image: postgres:13
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "15432:5432"
      